name: ascii_me

proportion_mutation_ga: 0.5

# GA emitter
iso_sigma: 0.005
line_sigma: 0.05

# PG emitter
buffer_sample_batch_size: 1
no_epochs: 32
learning_rate: 3e-3
discount_rate: 0.99
clip_param: 0.2
activation: tanh
no_neurons: 64
greedy: 0
cosine_similarity: True
std: 2
