name: memes

num_evaluations: 1_000_000
fixed_init_state: False
discard_dead: False

iso_sigma: 0.01
line_sigma: 0.1
crossover_percentage: 1.0


# ES Parameters
sample_number: 512 # Num samples for gradient estimate
sample_sigma: 0.02
sample_mirror: True # Use mirroring sampling
sample_rank_norm: True # Use normalisation
num_in_optimizer_steps: 1 # Num gradient step per generation
adam_optimizer: True
learning_rate: 0.01
l2_coefficient: 0.0  # coefficient for regularisation
novelty_nearest_neighbors: 10
use_novelty_archive: False # if 1 use repertoire for novelty
use_novelty_fifo: True # if 1 use fifo archive for novelty
fifo_size: 50000 # size of the fifo buffer
proportion_explore: 0.5 # if simultaneous, proportion of exploit-explore
num_generations_stagnate: 32
scan_batch_size: 128
scan_novelty: 2048