name: ppoish_me_trans

proportion_mutation_ga: 0.5

# GA emitter
iso_sigma: 0.005
line_sigma: 0.05

# PG emitter
buffer_sample_batch_size: 128
grad_steps: 16
learning_rate: 3e-4
discount_rate: 0.99
clip_param: 0.2
max_grad_norm: 0.5
constant_std: False
std: 0.5
activation: tanh
no_neurons: 128
buffer_size: 512000
alternate_no: 500
alternate: False