name: ppoish_me

proportion_mutation_ga: 0.5

# GA emitter
iso_sigma: 0.005
line_sigma: 0.05


# purePPO emitter
GREEDY_AGENTS: 1
LR: 1e-3
NUM_ENVS: 256
NUM_STEPS: 80
TOTAL_TIMESTEPS: 5e7
UPDATE_EPOCHS: 4
NUM_MINIBATCHES: 32
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.2
ENTROPY_COEFF: 0.0
VF_COEFF: 0.5
MAX_GRAD_NORM: 0.5
ACTIVATION: tanh
ANNEAL_LR: False
NORMALIZE_ENV: False
NO_ADD: 1
NO_NEURONS: 64

# PG emitter
buffer_sample_batch_size: 2
buffer_add_batch_size: 512
no_epochs: 16
learning_rate: 3e-4
discount_rate: 0.99
clip_param: 0.2
init_lecun: False
sample_trajectory: True
baseline_equal_parent_fitness: False

grad_steps: 16