hydra:
  job:
    chdir: True
  run:
    dir: ./output/${env.name}/${algo.name}/${now:%Y-%m-%d_%H%M%S_%f}

defaults:
  - _self_
  - env: ant_omni
  - algo: mcpg_me

seed: 42
num_iterations: 2000
batch_size: 512
num_samples: 8

# Archive
num_init_cvt_samples: 50000
num_centroids: 1024
policy_hidden_layer_sizes: [64, 64]
HPC: False

# testing
