hydra:
  job:
    chdir: True
  run:
    dir: ./output/${qd.algo}/${now:%Y-%m-%d_%H%M%S_%f}


seed: 0
algo: me
env: ...

num_generations: 20
log_period: 40
batch_size: 256

# Archive
num_init_cvt_samples: 50_000
num_centroids: 1024

# GA emitter
iso_sigma: 0.005
line_sigma: 0.05
