hydra:
  job:
    chdir: True
  run:
    dir: ./Results/${env.name}/${algo.name}/${now:%Y-%m-%d_%H%M%S_%f}

defaults:
  - _self_
  - env: halfcheetah_uni
  - algo: me

seed: 1
num_iterations: 2000
batch_size: 512
num_samples: 16

# Archive
num_init_cvt_samples: 50000
num_centroids: 1024
policy_hidden_layer_sizes: [128, 128]