hydra:
    job:
        chdir: True
    run:
        dir: /workspace/output/${env_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
    - _self_
    - env: ant_uni

# Env config
alg_name: rein-me
seed: 0
env_name: ant_uni
episode_length: 1000
policy_hidden_layer_sizes: [128, 128]
# ME config
num_evaluations: 0
num_iterations: 250
num_samples: 1
batch_size: 256
fixed_init_state: False
discard_dead: False
# Grid config
grid_shape: [50, 50]
num_init_cvt_samples: 50000
num_centroids: 1296
# Log config
log_period: 400
store_repertoire: True
store_repertoire_log_period: 800

iso_sigma: 0.005
line_sigma: 0.05

# REINFORCE Parameters
proportion_mutation_ga: 0.5
rollout_number: 64 # Num of episodes used for gradient estimate
num_rein_training_steps: 10 # Num gradient steps per generation
buffer_size: 102400 # Size of the replay buffer
adam_optimizer: True
learning_rate: 1e-2
discount_rate: 0.99
temperature: 0.